Update readme.md
The download script results in error: ImportError: cannot import name 'soft_unicode' from 'markupsafe'
This is because the function was removed after version 2.0.1